// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNUnitWeb.Data;

#nullable disable

namespace MyNUnitWeb.Migrations
{
    [DbContext(typeof(WebData))]
    partial class WebDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MyNUnitWeb.Model.TestClassModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestRunModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestRunModelId");

                    b.ToTable("TestClasses");
                });

            modelBuilder.Entity("MyNUnitWeb.Model.TestDetailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExecutionTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoreMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestClassModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestClassModelId");

                    b.ToTable("TestDetails");
                });

            modelBuilder.Entity("MyNUnitWeb.Model.TestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IgnoredTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassedTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("MyNUnitWeb.Model.TestClassModel", b =>
                {
                    b.HasOne("MyNUnitWeb.Model.TestRun", "TestRun")
                        .WithMany("TestClasses")
                        .HasForeignKey("TestRunModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("MyNUnitWeb.Model.TestDetailModel", b =>
                {
                    b.HasOne("MyNUnitWeb.Model.TestClassModel", "TestClass")
                        .WithMany("TestDetails")
                        .HasForeignKey("TestClassModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestClass");
                });

            modelBuilder.Entity("MyNUnitWeb.Model.TestClassModel", b =>
                {
                    b.Navigation("TestDetails");
                });

            modelBuilder.Entity("MyNUnitWeb.Model.TestRun", b =>
                {
                    b.Navigation("TestClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
